# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='twirp.example.haberdasher',
  syntax='proto3',
  serialized_options=_b('Z\"github.com/example/rpc/haberdasher'),
  serialized_pb=_b('\n\rservice.proto\x12\x19twirp.example.haberdasher\"\x16\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\"0\n\x03Hat\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"\x17\n\x06\x44ollar\x12\r\n\x05value\x18\x01 \x01(\x02\x32\x62\n\nDollarRate\x12T\n\rGetDollarRate\x12 .twirp.example.haberdasher.Empty\x1a!.twirp.example.haberdasher.DollarB$Z\"github.com/example/rpc/haberdasherb\x06proto3')
)




_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='twirp.example.haberdasher.Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inches', full_name='twirp.example.haberdasher.Size.inches', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=66,
)


_HAT = _descriptor.Descriptor(
  name='Hat',
  full_name='twirp.example.haberdasher.Hat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='twirp.example.haberdasher.Hat.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='twirp.example.haberdasher.Hat.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='twirp.example.haberdasher.Hat.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=116,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='twirp.example.haberdasher.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=125,
)


_DOLLAR = _descriptor.Descriptor(
  name='Dollar',
  full_name='twirp.example.haberdasher.Dollar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='twirp.example.haberdasher.Dollar.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['Size'] = _SIZE
DESCRIPTOR.message_types_by_name['Hat'] = _HAT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Dollar'] = _DOLLAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), dict(
  DESCRIPTOR = _SIZE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:twirp.example.haberdasher.Size)
  ))
_sym_db.RegisterMessage(Size)

Hat = _reflection.GeneratedProtocolMessageType('Hat', (_message.Message,), dict(
  DESCRIPTOR = _HAT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:twirp.example.haberdasher.Hat)
  ))
_sym_db.RegisterMessage(Hat)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:twirp.example.haberdasher.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Dollar = _reflection.GeneratedProtocolMessageType('Dollar', (_message.Message,), dict(
  DESCRIPTOR = _DOLLAR,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:twirp.example.haberdasher.Dollar)
  ))
_sym_db.RegisterMessage(Dollar)


DESCRIPTOR._options = None

_DOLLARRATE = _descriptor.ServiceDescriptor(
  name='DollarRate',
  full_name='twirp.example.haberdasher.DollarRate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=152,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDollarRate',
    full_name='twirp.example.haberdasher.DollarRate.GetDollarRate',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DOLLAR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOLLARRATE)

DESCRIPTOR.services_by_name['DollarRate'] = _DOLLARRATE

# @@protoc_insertion_point(module_scope)
